language: python
python:
  - "3.6"
before_install:
  - pip install pipenv==2018.7.1
install:
  - pipenv install --dev --system --deploy
  - python manage.py migrate
  - python manage.py collectstatic
script:
  - python manage.py test
